DROP TABLE IF EXISTS `PROJECT`;
CREATE TABLE PROJECT(
	NAME	VARCHAR(255)	NOT NULL,
	URL		VARCHAR(255)	NOT NULL,
	LOCALPATH	VARCHAR(255)	NOT NULL,
	create_time INTEGER NOT NULL,
	num_commits INTEGER NOT NULL,
	LICENSES	VARCHAR(255),
	PRIMARY KEY ( URL )
);


DROP TABLE IF EXISTS `COMMIT`;
CREATE TABLE COMMIT(
	SHA1	VARCHAR(255)	NOT NULL,
	PROJECT_URL		VARCHAR(255)	NOT NULL,
	DEVELOPER_EMAIL	VARCHAR(255),
	TIME	INTEGER NOT NULL,
	COMMIT_MSG	VARCHAR(255),
	commit_msglen INTEGER NOT NULL,
	isBugFix BOOL	NOT NULL,
	PRIMARY KEY ( SHA1 )
);

DROP TABLE IF EXISTS `ASTROOT`;
CREATE TABLE ASTROOT(
	LOCALFILE_PATH	VARCHAR(255)	NOT NULL,
	PROJECT_URL		VARCHAR(255)	NOT NULL,
	COMMIT_SHA1 	VARCHAR(255)	NOT NULL,
	LICENSE			VARCHAR(255),
	PACKAGEDECLARE VARCHAR(255),
	TYPEDECLARE_NAME VARCHAR(255)
);

DROP TABLE IF EXISTS `ASTROOT_IMPORT`;
CREATE TABLE ASTROOT_IMPORT(
	LOCALFILE_PATH	VARCHAR(255)	NOT NULL,
	PROJECT_URL		VARCHAR(255)	NOT NULL,
	COMMIT_SHA1 	VARCHAR(255)	NOT NULL,
	IMPORTDECLARE			VARCHAR(255)	NOT NULL
);

DROP TABLE IF EXISTS `ASTTYPEDECLARE`;
CREATE TABLE ASTTYPEDECLARE(
	LOCALFILE_PATH	VARCHAR(255)	NOT NULL,
	PROJECT_URL		VARCHAR(255)	NOT NULL,
	COMMIT_SHA1 	VARCHAR(255)	NOT NULL,
	TYPEDECLARE_NAME VARCHAR(255)	NOT NULL,
	MODIFIERS VARCHAR(255),
	SUPERCLASS	VARCHAR(255)	
);

DROP TABLE IF EXISTS `ASTTYPEDECLARE_NESTEDTYPE`;
CREATE TABLE ASTTYPEDECLARE_NESTEDTYPE(
	LOCALFILE_PATH	VARCHAR(255)	NOT NULL,
	PROJECT_URL		VARCHAR(255)	NOT NULL,
	COMMIT_SHA1 	VARCHAR(255)	NOT NULL,
	OUTERTYPE_NAME VARCHAR(255)	NOT NULL,
	INNERTYPE_NAME VARCHAR(255)	NOT NULL
	
);

DROP TABLE IF EXISTS `ASTFIELDDECLARE`;
CREATE TABLE ASTFIELDDECLARE(
	LOCALFILE_PATH	VARCHAR(255)	NOT NULL,
	PROJECT_URL		VARCHAR(255)	NOT NULL,
	COMMIT_SHA1 	VARCHAR(255)	NOT NULL,
	TYPE	VARCHAR(255)	NOT NULL,
	NAME	VARCHAR(255)	NOT NULL,
	INITIALIZER 	VARCHAR(255),
	MODIFIERS VARCHAR(255)	
);

DROP TABLE IF EXISTS `ASTMETHODDECLARE`;
CREATE TABLE ASTMETHODDECLARE(
	LOCALFILE_PATH	VARCHAR(255)	NOT NULL,
	PROJECT_URL		VARCHAR(255)	NOT NULL,
	COMMIT_SHA1 	VARCHAR(255)	NOT NULL,
	ISCONSTRUCTOR	BOOL	NOT NULL,
	RETURN_TYPE	VARCHAR(255),
	NAME	VARCHAR(255)	NOT NULL,
	PARAMETERS 	VARCHAR(255),
	MODIFIERS VARCHAR(255)	
);

